language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - "pip install defusedxml"
  - "pip install python-dateutil"
  - "pip install six"
  - "pip install coveralls"

script:
  coverage run --source=parserutils -m unittest parserutils.tests.tests

after_success:
  coveralls