language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

install:
  - "pip install defusedxml"
  - "pip install python-dateutil"
  - "pip install mock"
  - "pip install coveralls"

script:
  coverage run --omit=parserutils/tests/*.py --source=parserutils -m unittest parserutils.tests

after_success:
  coveralls