language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

install:
  - "pip install defusedxml"
  - "pip install python-dateutil"
  - "pip install six"
  - "pip install coveralls"

script:
  coverage run --source=parserutils -m unittest parserutils.tests.tests

after_success:
  coveralls