language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - "pip install defusedxml"
  - "pip install python-dateutil"
  - "pip install six"

script: "python setup.py test"

after_success:
  - coveralls || echo "!! intermittent coveralls failure"